name: "Test Cleanup Action"

on: [push]

jobs:
  test-cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: ./ 
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
