name: "Test Cleanup Action"

on: [push]

jobs:
  docker-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Docker Cleanup
        uses: ikrambagban/docker-pruner@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          thresholdDays: 3
